version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "8080:80"     # frontend on http://localhost:8080
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "5000:5000"   # backend API on http://localhost:5000
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
